# Window
SCREEN_TITLE = "Body Tracking Avatar"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Sprites
SPRITE_SCALE = 2

# Part Indexes
HEAD_INDEX = 0
UPPER_LEFT_TORSO = 12
LOWER_LEFT_TORSO = 24
UPPER_RIGHT_TORSO = 11
LOWER_RIGHT_TORSO = 23
LEFT_HAND_FINGER_INDEX = 18
LEFT_HAND_WRIST_INDEX = 16
RIGHT_HAND_FINGER_INDEX = 17
RIGHT_HAND_WRIST_INDEX = 15
LEFT_FOOT_HEEL_INDEX = 29
LEFT_FOOT_TOE_INDEX = 31
RIGHT_FOOT_TOE_INDEX = 32
RIGHT_FOOT_HEEL_INDEX = 30